- name: Build
  env:
    scheme: ${{ 'default' }}
    platform: ${{ 'iOS Simulator' }}
  run: |
    if [ $scheme = default ]; then scheme=$(cat default); fi
    xcodebuild build-for-testing \
      -project datafight.xcodeproj \
      -scheme "$scheme" \
      -destination 'platform=iOS Simulator,OS=18.0,name=iPad Pro 13-inch (M4)' \
      CODE_SIGNING_ALLOWED=NO \
      -skipPackagePluginValidation | xcpretty

- name: Test with Firebase Emulator
  env:
    scheme: ${{ 'default' }}
    platform: ${{ 'iOS Simulator' }}
    IS_TESTING: "YES"
    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-key.json
  run: |
    if [ $scheme = default ]; then scheme=$(cat default); fi
    firebase emulators:exec --only firestore,auth,storage --project datafight-5d0cf \
      "xcodebuild test-without-building \
        -project datafight.xcodeproj \
        -scheme \"$scheme\" \
        -destination 'platform=iOS Simulator,OS=18.0,name=iPad Pro 13-inch (M4)' \
        CODE_SIGNING_ALLOWED=NO \
        -skipPackagePluginValidation \
        -retry-tests-on-failure \
        -test-timeouts-enabled NO \
        -timeout=1800 | xcpretty"
