name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Node.js (updated to version 20)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install xcpretty (for Xcode build formatting)
      - name: Install xcpretty
        run: |
          gem install xcpretty

      # Install Firebase CLI globally
      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      # Set up the latest stable version of Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      # List available simulators (for debugging)
      - name: List Available Simulators
        run: |
          xcrun simctl list devices

      # Use Firestore Emulator action from GitHub Marketplace
      - name: Start Firestore Emulator
        uses: ikemtz/firestore-emulator-action@v2 # Using the action from GitHub Marketplace
        with:
          projectId: datafight-5d0cf
          port: 8080 # Optional, you can specify the port if needed

      # Start the simulator manually
      - name: Start iOS Simulator
        run: |
          xcrun simctl boot "iPad Pro (12.9-inch) (6th generation)"

      # Wait for the simulator to fully boot
      - name: Wait for Simulator to Boot
        run: sleep 30

      # Verify Simulator State
      - name: Verify Simulator State
        run: |
          xcrun simctl list devices | grep "iPad Pro (12.9-inch) (6th generation)"

      # Resolve Swift Package Dependencies
      - name: Resolve Swift Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies \
            -project datafight.xcodeproj

      # Build and Test with additional timeout and environment variable
      - name: Build and Test
        run: |
          xcodebuild test \
            -project datafight.xcodeproj \
            -scheme datafight \
            -destination 'platform=iOS Simulator,name=iPad Pro 13-inch (M4) (6th generation)' \
            -destination-timeout 60 \
            CODE_SIGNING_ALLOWED=NO \
            -skipPackagePluginValidation \
            -retry-tests-on-failure \
            -test-timeouts-enabled NO \
            -timeout=300
        env:
          IS_TESTING: "yes" # Define the environment variable for testing mode

      # Debug Directory Structure
      - name: Debug Directory Structure
        run: |
          ls -R ${{ github.workspace }}
          ls -R ${{ github.workspace }}/build

      # Package App and Tests (if needed)
      - name: Package App and Tests
        run: |
          mkdir -p Payload
          cp -r ${{ github.workspace }}/build/Debug-iphonesimulator/datafight.app Payload/
          zip -r app.ipa Payload

          cd ${{ github.workspace }}/build/Debug-iphonesimulator
          zip -r ${{ github.workspace }}/tests.zip datafightTests.xctest
