name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install xcpretty
        run: |
          gem install xcpretty

      - name: Install Firebase CLI globally
        run: |
          npm install -g firebase-tools

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: List Available Simulators
        run: |
          xcrun simctl list devices

      - name: Check Xcode version
        run: |
          xcodebuild -version

      - name: Resolve Swift Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies \
            -project datafight.xcodeproj

      # Start Firebase Emulator Suite (with logging)
      - name: Start Firebase Emulator Suite
        run: |
          firebase emulators:start --only firestore,auth,storage --project datafight-5d0cf --import=./emulator-data --export-on-exit=./emulator-data --token ${{ secrets.FIREBASE_TOKEN }} > firebase-emulator-log.txt &
        
      - name: Wait for Firebase Emulator to Start
        run: sleep 10

      - name: Show Firebase Emulator Logs
        run: cat firebase-emulator-log.txt

      - name: Create Build Directory
        run: |
          mkdir -p ${{ github.workspace }}/build/Debug-iphonesimulator

      - name: Debug Project Files
        run: |
          ls -R ${{ github.workspace }}/datafight.xcodeproj

      - name: Build and Test
        run: |
          xcodebuild test \
            -project datafight.xcodeproj \
            -scheme datafight \
            -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (6th generation)' \
            CODE_SIGNING_ALLOWED=NO \
            -skipPackagePluginValidation \
            -retry-tests-on-failure \
            -test-timeouts-enabled NO \
            -timeout=300

      - name: Stop Firebase Emulator Suite
        run: |
          firebase emulators:stop

      - name: Debug Directory Structure
        run: |
          ls -R ${{ github.workspace }}
          ls -R ${{ github.workspace }}/build

      - name: Package App and Tests
        run: |
          mkdir -p Payload
          cp -r ${{ github.workspace }}/build/Debug-iphonesimulator/datafight.app Payload/
          zip -r app.ipa Payload

          cd ${{ github.workspace }}/build/Debug-iphonesimulator
          zip -r ${{ github.workspace }}/tests.zip datafightTests.xctest

      - name: Upload to Firebase Test Lab
        uses: w9jds/firebase-action@master
        with:
          args: >
            firebase test ios run
            --app app.ipa
            --test tests.zip
            --device model=iPadPro12,version=17.0,locale=en_US,orientation=portrait
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
